language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r test_requirements.txt
  - pip install -e .[pandas]
script:
  - pytest test/ --cov-config=.coveragerc --cov=svl/
after_success:
  - coveralls