language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r test_requirements.txt
  - pip install -e .
script:
  - pytest test --cov=svl
  - flake8 svl
  - flake8 test
after_success:
  - coveralls