site_name: SVL Documentation
repo_name: 'timothyrenner/svl'
repo_url: 'https://github.com/timothyrenner/svl'
theme:
  name: 'material'
  logo:
    icon: 'show_chart'
nav:
  - Home: 'index.md'
  - Tutorials:
    - Basic SVL: 'tutorials/basic_svl.md'
    - Advanced SVL: 'tutorials/advanced_svl.md'
  - Reference:
    - Syntax: 'reference/syntax_reference.md'
    - Under the Hood: 'reference/under_the_hood.md'
  - Sample Visualizations:
    - Quickstart: 'sample_visualizations/quickstart_example.html'
    - Basic SVL - Chart Types: 'sample_visualizations/basic_tutorial_chart_types.html'
    - Basic SVL - Customizing Charts: 'sample_visualizations/basic_tutorial_customizing_charts.html'
    - Basic SVL - Plot Arrangement: 'sample_visualizations/basic_tutorial_plot_arrangement_3.html'